trigger:
- master
pr:
- master
pool:
  name: Hosted VS2017
steps:
- script: 'node .\common\scripts\install-run-rush.js install'
  displayName: 'rush install'

- script: 'node .\common\scripts\install-run-rush.js test'
  displayName: 'rush test'